name: Auto Download XML - DailyScheduler(12:30 AM)

on:
  schedule:
    - cron: '30 0 * * *'  # Runs at 12:30 AM UTC daily
    - cron: '35 23 * * *'  # Runs at 11:35 PM UTC daily (Get updated XML)

  workflow_dispatch:

jobs:
  run_script:
    name: Run Python Script
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Choose your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r script_requriments.txt  # If you have any dependencies, replace with your requirements file

      - name: Run Python script
        run: python scripts/download_xml.py  # Replace with the path to your Python script
