name: Manual Python Job - XML

on:
  workflow_dispatch:
    inputs:
      message1:
        description: 'old_date'
        required: true
      message2:
        description: 'new_date'
        required: true
      message3:
        description: 'find_date'
        required: true

jobs:
  run_python_script:
    name: Run - Get XML Diffrece file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install numpy
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python Script
        run: python get_xml_diffrence.py --old_date ${{ github.event.inputs.message1 }} --new_date ${{ github.event.inputs.message2 }} --find_date ${{ github.event.inputs.message3 }}
