name: Daily Python Script - Delete old XML

on:
  schedule:
    - cron: '50 0 * * *'  # Runs at 12:30 AM UTC daily
  workflow_dispatch:

jobs:
  run_script:
    name: Run Python Script
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Choose your Python version here

      - name: Run Python script
        run: python scripts/delete_old_csv_xml_files.py  # Replace with the path to your Python script
